import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './Redux/storeProvider';
import { Suspense } from 'react';
import Loadingcompante from './loading';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <Suspense fallback={<Loadingcompante />}>
          <body className={inter.className}>{children}</body>
        </Suspense>
      </StoreProvider>
    </html>
  );
}
